name: Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      firmware:
        description: 'Direct Firmare Link'
        required: true
      filename:
        description: 'Fill as it is file name of zip/ozip with .zip/.ozip'
        required: true

env:
  FIRMWARE: ${{ github.event.inputs.firmware }}
  FILENAME: ${{ github.event.inputs.filename }}
  TZ: Asia/Kolkata

jobs:
  decrypt-ozip:
      runs-on: ubuntu-20.04

      steps:
      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main         

      - name: Clone Dumpyara and Download Firmware which Has to be Dumped
        run: |
             git clone --depth=1 https://github.com/sarthakroy2002/dumpyara dumpyara
             cd dumpyara
             aria2c $FIRMWARE
             sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool axel gawk aria2 detox cpio rename expect -y
             sudo pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen

      - name: Firmware is now Gonna Dump
        run: |
             cd dumpyara
             bash dumpyara.sh $FILENAME ${{ secrets.GKEY }}
