name: Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Direct Firmare Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TZ: Asia/Kolkata

jobs:
  dumper-workflow:
      runs-on: ubuntu-20.04

      steps:
      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main         

      - name: Add configs
        run: 
             export GIT_TRACE_PACKET=1
             export GIT_TRACE=1
             export GIT_CURL_VERBOSE=1

      - name: Clone Dumpyara and Download Firmware which Has to be Dumped
        run: |
             git clone --depth=1 https://github.com/DumprX/DumprX
             cd DumprX
             sudo apt update -y && sudo apt upgrade -y
             sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract device-tree-compiler liblzma-dev python3-pip brotli liblz4-tool axel gawk aria2 detox cpio rename expect -y
             sudo pip3 install backports.lzma protobuf pycrypto docopt zstandard twrpdtgen extract-dtb
             sudo pip3 install --upgrade protobuf==3.20.0
             echo "${{ secrets.GORG }}" > .github_orgname
             echo "${{ secrets.GKEY }}" > .github_token

      - name: Firmware is now Gonna Dump
        run: |
             cd DumprX
             bash setup.sh
             bash dumper.sh $LINK
