name: Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      firmware:
        description: 'Direct Firmare Link'
        required: true
      filename:
        description: 'Fill as it is file name of zip/ozip with .zip/.ozip'
        required: true

env:
  FIRMWARE: ${{ github.event.inputs.firmware }}
  FILENAME: ${{ github.event.inputs.filename }}
  TZ: Asia/Kolkata

jobs:
  decrypt-ozip:
      runs-on: ubuntu-20.04

      steps:
      - name: Clone Repo 
        run: git clone --depth=1 https://github.com/sarthakroy2002/dumpyara dumpyara

      - name: Download Firmware which Has to be Dumped
        run: |
             cd dumpyara
             aria2c $FIRMWARE
             bash setup.sh expect -y

      - name: Firmware is now Gonna Dump
        run: |
             bash dumpyara.sh $FILENAME ${{ secrets.GKEY }}
